#!/usr/bin/env bash
# =============================================================================
# control-plane startup script (terraform templatefile target).
#
# Runs on every boot of oj-control-plane via VM metadata `startup-script`.
# Idempotent: each step is a no-op if already done. Safe to re-run.
#
# Template variables interpolated by terraform:
#   ${ar_url}              e.g. asia-south1-docker.pkg.dev/online-judge-hk/oj-images
#   ${region}              e.g. asia-south1
#   ${jwt_secret}          48-byte random secret (terraform random_password)
#   ${compose_yaml_b64}    base64-encoded control-plane-compose.yml
#   (init_sql_b64 was removed in V3 — Flyway in api-gateway owns the schema)
#   ${gcs_bucket_name}     GCS bucket holding per-ordinal input/expected objects
#   ${gcs_signer_secret}   Secret Manager secret id holding the signer SA JSON key
#
# All other config (kafka host IP, AR URL, JWT secret) lands in /opt/oj/.env
# which the systemd unit sources via `EnvironmentFile=`.
# =============================================================================

set -euo pipefail

LOG=/var/log/oj-startup.log
exec > >(tee -a "$LOG") 2>&1
echo "[oj-startup] $(date -Iseconds) — control-plane.sh begin"

# ---------- Docker install (idempotent) -------------------------------------
if ! command -v docker >/dev/null 2>&1; then
  echo "[oj-startup] installing docker engine + compose plugin"
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -y
  apt-get install -y ca-certificates curl gnupg lsb-release
  install -m 0755 -d /etc/apt/keyrings
  # --batch --no-tty: gpg 2.x in systemd-run startup scripts has no
  # controlling terminal; without these flags it tries to open /dev/tty
  # for status messages and dies with "cannot open '/dev/tty'".
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
    gpg --batch --no-tty --yes --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -y
  apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  systemctl enable --now docker
  usermod -aG docker hemant || true
else
  echo "[oj-startup] docker already installed: $(docker --version)"
fi

# ---------- gcloud (for AR auth helper) -------------------------------------
if ! command -v gcloud >/dev/null 2>&1; then
  echo "[oj-startup] installing google-cloud-cli"
  curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | \
    gpg --batch --no-tty --yes --dearmor -o /usr/share/keyrings/cloud.google.gpg
  echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" \
    > /etc/apt/sources.list.d/google-cloud-sdk.list
  apt-get update -y
  apt-get install -y google-cloud-cli
fi

# ---------- Artifact Registry auth ------------------------------------------
# The VM's attached service account has artifactregistry.reader. The gcloud
# auth-configure-docker helper sets up a credential helper that pulls a fresh
# OAuth token on every `docker pull`, so no key file is needed.
AR_REGISTRY="$(echo '${ar_url}' | cut -d/ -f1)"
echo "[oj-startup] configuring docker auth for $AR_REGISTRY"
gcloud auth configure-docker "$AR_REGISTRY" --quiet

# ---------- Drop compose + .env ---------------------------------------------
install -d -m 0755 /opt/oj

echo '${compose_yaml_b64}' | base64 -d > /opt/oj/control-plane-compose.yml
# init.sql is no longer injected here — V3 retired the two-database split.
# api-gateway's Flyway migrations own the schema on the `onlinejudge` DB.

# Internal IP of this VM, discovered from the GCE metadata service — used as
# the advertised Kafka host for off-VM clients (i.e. the compute VM).
INTERNAL_IP="$(curl -sfH 'Metadata-Flavor: Google' \
  http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/ip)"

cat > /opt/oj/.env <<EOF
# Generated by control-plane.sh on $(date -Iseconds). Do not edit by hand —
# changes are clobbered on next boot. Tweak terraform vars instead.
AR_URL=${ar_url}
KAFKA_HOST_EXTERNAL=$INTERNAL_IP
JWT_SECRET=${jwt_secret}
REGION=${region}
GCS_BUCKET=${gcs_bucket_name}
EOF
chmod 0600 /opt/oj/.env

# ---------- Fetch problem-service signer key from Secret Manager ------------
# problem-service signs short-lived V4 GCS download URLs. The JCA needs the
# SA's private key on disk — ADC tokens won't work. We fetch the SA JSON key
# from Secret Manager (where terraform pushed it) on every boot. Compose
# mounts /opt/oj/gcs-signer.json into the container as /var/secrets/gcs-signer.json.
echo "[oj-startup] fetching problem-service signer key from Secret Manager"
if gcloud secrets versions access latest --secret="${gcs_signer_secret}" \
     > /opt/oj/gcs-signer.json.new 2>/dev/null; then
  chmod 0400 /opt/oj/gcs-signer.json.new
  mv /opt/oj/gcs-signer.json.new /opt/oj/gcs-signer.json
  echo "[oj-startup] gcs-signer.json ready"
else
  echo "[oj-startup] WARN: secret ${gcs_signer_secret} not accessible yet — problem-service will fail GCS signing"
  rm -f /opt/oj/gcs-signer.json.new
fi

# ---------- Pre-pull AR image (so first start isn't blocked on a 200 MB pull) -
echo "[oj-startup] pre-pulling api-gateway image"
docker pull ${ar_url}/api-gateway:latest || \
  echo "[oj-startup] WARN: pre-pull failed; compose-up will retry"

# ---------- systemd unit ----------------------------------------------------
cat > /etc/systemd/system/oj-control-plane.service <<'UNIT'
[Unit]
Description=Online Judge — control-plane docker-compose stack
After=docker.service network-online.target
Requires=docker.service
Wants=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
EnvironmentFile=/opt/oj/.env
WorkingDirectory=/opt/oj
ExecStart=/usr/bin/docker compose -f /opt/oj/control-plane-compose.yml up -d --remove-orphans
ExecStop=/usr/bin/docker compose -f /opt/oj/control-plane-compose.yml down
TimeoutStartSec=600

[Install]
WantedBy=multi-user.target
UNIT

systemctl daemon-reload
systemctl enable oj-control-plane.service
systemctl restart oj-control-plane.service

echo "[oj-startup] $(date -Iseconds) — control-plane.sh done"
