-- =============================================================================
-- !!! OBSOLETE — DO NOT USE !!!
--
-- This file used to be mounted into the CockroachDB container's
-- /docker-entrypoint-initdb.d/ and bootstrapped the `onlinejudge` database
-- on a fresh volume. Pre-V3 we ran a two-database split: api-gateway lived
-- on `defaultdb` (managed by its own Flyway migrations) and problem-service
-- lived on `onlinejudge` (managed by THIS file). That split caused recurring
-- schema-drift incidents.
--
-- V3 collapses the split. Flyway in api-gateway is now the single source of
-- truth for ALL schema (api-gateway write-path tables AND problem-service
-- read tables). See:
--
--     api-gateway/src/main/resources/db/migration/V1__init.sql
--     api-gateway/src/main/resources/db/migration/V2__add_region.sql
--     api-gateway/src/main/resources/db/migration/V3__unify_schema.sql
--
-- For the one-off data move from defaultdb -> onlinejudge, see:
--
--     infra/scripts/db-migration-onlinejudge.sql
--
-- The historical content below is preserved for archaeological reference
-- only. It is not executed anywhere — the docker-compose mount and the
-- terraform templatefile injection that fed it into the control-plane VM
-- were both removed in V3.
-- =============================================================================

-- (Historical) CREATE DATABASE IF NOT EXISTS onlinejudge;
-- (Historical) USE onlinejudge;
--
-- (Historical) CREATE TABLE users (
--     id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--     username STRING UNIQUE NOT NULL,
--     created_at TIMESTAMP DEFAULT now()
-- );
--
-- (Historical) CREATE TABLE problems (
--     id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--     title STRING NOT NULL,
--     time_limit_ms INT NOT NULL,
--     memory_limit_mb INT NOT NULL,
--     points INT NOT NULL,
--     created_at TIMESTAMP NOT NULL DEFAULT now(),
--     updated_at TIMESTAMP NOT NULL DEFAULT now()
-- );
--
-- (Historical) CREATE TABLE test_cases (
--     id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--     problem_id UUID NOT NULL REFERENCES problems(id),
--     ordinal INT NOT NULL,
--     input_gcs_key STRING NOT NULL,
--     expected_output_gcs_key STRING NOT NULL,
--     UNIQUE (problem_id, ordinal)
-- );
--
-- (Historical) submissions/outbox_events/idempotency_keys were also defined
-- here but were never actually used — api-gateway always wrote to defaultdb
-- pre-V3. V3 keeps the column types of the gateway's V1+V2 schema
-- (outbox_events.payload TEXT, not JSONB; outbox_events.published BOOLEAN;
-- submissions.gateway_ts_ms BIGINT) since those are what the JPA entities
-- expect.
